### ISSUE TITLE
Error 500 after install this module

### ISSUE THREAD

**Issue by Sasni** [PululuK/democustomfields17#1]
Hi, I'm using Prestashop version 1.7.7.7
I downloaded your module but I can't install it because I get an error.
So I copied the democustomfields17 forlder to the modules directory.
This behavior causes the Error 500 problem
In line 7 there is:
require_once __DIR __. '/ vendor / autoload.php';
Shouldn't there be:
require_once _PS_ROOT_DIR _. '/ vendor / autoload.php';
because the __DIR__ variable points to the module (directory modules/democustomfields17/vendor[...]) And I think we want to load the file from the main directory (/vendor[...])
If I am wrong, correct me please.
![image](https://user-images.githubusercontent.com/3370929/135530525-48d59a24-7a26-44be-997f-ed8d2f69411b.png)

**Comment by PululuK** [comment]
Hi @Sasni 

See please https://github.com/PululuK/democustomfields17#install

**Comment by Sasni** [comment]
Hello, thanks for your reply. 
Are you planning a further expansion with a database connection so that you can save the values entered in additional fields?

**Comment by vmulot** [comment]
@Sasni did you manage to save values  & display them in front ? Thanks

**Comment by PululuK** [comment]
> @Sasni did you manage to save values & display them in front ? Thanks

Hi @vmulot  @Sasni can you please open an issue to request this feature  ?
