### ISSUE TITLE
Aide à l'installation et l'adaptation

### ISSUE THREAD

**Issue by EliottCrmx** [PululuK/democustomfields17#10]
**Describe the bug**
Bonjour,  (contacté par mail hier)

Si j'ai bien compris, on ne peut pas l'installer via le gestionnaire de module de Prestashop, c'est pourquoi j'ai essayé de suivre vos indication dans la partie 'Install' sans succès, peut-on l'installer tel quel ou doit-on l'adapter avant ?
Pour les commandes de l'install, dois-je utilisé une console git ou powershell ...? sous cmd certaines commandes ne sont pas reconnues

**Desktop**
 - OS: W10
 - Browser: Mozilla
 - Version Prestashop : 1.7.8.2
 - Pour l'instant en local

**Additional context**
Actuellement en alternance pour mes études, j'aimerai vraiment comprendre le fonctionnement de prestashop car pour le moment je n'ai pas forcement encore tout saisie au sujet des class et controllers de prestashop. (Je gère pourtant assez bien le MVC, ici j'ai du mal à réaliser mes modifications sur prestashop en général)

Merci d'avance pour votre aide.

**Comment by PululuK** [comment]
Bonjour @EliottCrmx 


## Install

Pour l'installation du module je viens de faire un relase beta que vous pouvez tester et me faire des retours  (Voir ici https://github.com/PululuK/democustomfields17/releases/tag/v1.0.0-beta.1). Vous n'avez qu'à télécharger et installer directement depuis votre backoffice prestashop.

## Adapt

Tu peux me donner un example concret d'un champs que tu souhaites ajouter à ta fiche produit  pour que je puisse te fournir un example : 

- Le nom du champs 
- Le type du champs (et si traduisible ou pas)
- Indiquer où le champs doit s'afficher en BO (une capture si possible)
- Indiquer où le champs doit s'afficher en FO (capture si possible)

## Aides 

- Documentation technique prestashop : https://devdocs.prestashop.com/
- Tu peux discuter directement avec l'équipe Core ici : https://www.prestashop-project.org/slack/
- Ou avec la communauté ici : https://friends-of-presta.slack.com/ssb/redirect


ping @jf-viguier comment je fais pour l'inviter chez FoPs ?

N'hesite si t'as des questions

Pululu

**Comment by jf-viguier** [comment]
@PululuK @EliottCrmx le lien Slack sur le site https://friendsofpresta.org/
Welcome !

**Comment by EliottCrmx** [comment]
Wow, merci à vous deux !
J'ai bien réussi à l'installer depuis l'admin prestashop, j'aurai quelques questions :
- Pour l'instant c'est juste un input text c'est bien ça ?
- Y a t-il l'enregistrement dans la base de données ?
(j'ai testé mais rien de s'affiche sur la page produit j'imagine que c'est normal pour l'instant)
Je vous mets en pj un screen d'une page produit dans l'admin où de nouveau input son apprus, mais dont je ne comprends pas bien (hooks ?).

**Mon but**
Je travaille sur une marketplace (avec un module qui gère ça donc forcément les modifs ne sont pas évidentes),
je souhaiterai ajouter des champs de type time et MaterialChoiceTableType (dropdown checkbox) qui s'enregisterai sur ps_product, ces nouveau input doivent se trouver sur la page d'administration du produit côté vendeur

Merci pour l'invitation sur slack, je vais y aller !

![CaptureProduitVendeur](https://user-images.githubusercontent.com/53005233/158786564-838a0004-a985-4410-b647-a3175fbb7b98.PNG)
![CaptureAdmin1](https://user-images.githubusercontent.com/53005233/158786571-3769e902-1ef9-4333-8e17-8868b89960d7.PNG)
.

**Comment by EliottCrmx** [comment]
Re, 

Pour plus de précisions : le premier screen est la page ajout/modification produit du vendeur (vu que nous sommes sur une marketplace on a : le front client, le front 'administration' des vendeurs, et notre admin)
Dans le section 'retrait' [ouverte sur le screen] nous souhaiterions avoir des input time pour définir des horaires de retrait et un dropdown checkbox pour les jours de semaine dispo pour retrait. Naturellement il faut que tout cela soit enregistrer dans la base de données sur la table ps_product afin de pouvoir les afficher sur la page produit (front client) et aussi sûrement sur les mails.
Merci de votre aide pour mieux comprendre comment fonctionne prestashop.

PS : je n'arrive pas m'inscrire sur le groupe slack, qui à l'air super intéressant !
