### ISSUE TITLE
Affichage des variables concaténés en smarty n'affiche rien (e.g : {$product.democustomfields17.my_text_field_example} )

### ISSUE THREAD

**Issue by EliottCrmx** [PululuK/democustomfields17#11]
**Describe the bug**
Affichage des variables concaténés en smarty n'affiche rien (e.g : {$product.democustomfields17.my_text_field_example} )

Bonjour, désolé de revenir vers vous mais je n'arrive toujours pas à afficher mes data enregistrés avec ce que vous avez indiqué dans votre doc : 

{$product.democustomfields17.my_text_field_example}
{$product.democustomfields17.my_translatable_text_field_example }
{$product.democustomfields17.my_switch_field_example}

![Capture_screencode](https://user-images.githubusercontent.com/53005233/158997242-a6fa530d-fba1-46e9-96bf-60ec904188b7.PNG)
![Capturemodule](https://user-images.githubusercontent.com/53005233/158997249-f27af480-2ab0-4290-b311-0cfd4c585763.PNG)

Tout le reste fonctionne : input côté admin, envoie à la base de données mais pour la récupération sur la bdd et l'affichage ça bloque...
Si je comprends bien $product est la variable array qui récupère la table ps_product concaténé avec democustomfields17 (qui récupère la table ps_democustomfields17, mais où et comment ) concaténé avec le nom du champs. C'est bien ça ?

Merci encore

**Comment by PululuK** [comment]
Bonjour @EliottCrmx 

Je n'ai pas reussi à reproduire ce bug (testé sur 1.7.7.1)

# BO

![image](https://user-images.githubusercontent.com/16455155/158998684-7890686e-59c9-46a7-9bb1-034f2b387ab0.png)

# Core

/themes/mytheme/templates/catalog/product.tpl

```smarty
{var_dump($product.democustomfields17)}
```

# FO

![image](https://user-images.githubusercontent.com/16455155/158998929-2440f930-34ed-470c-a36b-504c2fad8d7e.png)



Merci d'indiquer la version de votre prestashoo dans les issues svp !

**Comment by sebastian-marinescu** [comment]
@EliottCrmx I have practically the same issue. Did you somehow manage to fix it and get some output in the frontend?
