### ISSUE TITLE
Adaptation du module

### ISSUE THREAD

**Issue by EliottCrmx** [PululuK/democustomfields17#12]
Bonjour,

désolé, c'est encore moi

Jusqu'ici ça fonctionne, maintenant je souhaiterai ajouter des champs (un dropdown-checkbox et un de type date) pour l'instant(par défaut) au nombre de trois (text, switch et textArea), la vue des input de votre module qui s'affiche dans l'admin n'a pas de tpl c'est ça ? alors où et comment puis-je faire mes modifications ?

Autre problèmatique : je souhaiterai afficher cette vue admin (de votre module) sur la vue/le front d'un autre module, j'ai pensé aux hooks mais il semblerai que la page de l'autre module ne soit pas accroché à un hook... auriez-vous une idée de comment procéder ?
Dois-je copier des fichiers de votre module et les placer dans l'autre module ?

Merci beaucoup pour toute l'aide déjà apporté.

**Comment by PululuK** [comment]
Bonjour,

Tu peux me fournir quelques captures d'ecran ? Où tu veux ajouter tes champs dans la fiche produit concretement en BO ?


Voici les differents types de champs que vous pouvez utiliser :

- https://symfony.com/doc/current/reference/forms/types.html
- https://devdocs.prestashop.com/1.7/development/components/form/types-reference/


Si vous souhaitez customiser les types de champs, voici le template : 

- `views/PrestaShop/democustomfields17/admin/product/customfields.html.twig`

Voir la documentantion : https://symfony.com/doc/current/form/form_customization.html

**Comment by EliottCrmx** [comment]
Pour le type du dropdown j'avais vu MaterialChoiceTableType dans https://devdocs.prestashop.com/1.7/development/components/form/types-reference/  mais comment l'utiliser ?

Ok pour les twig j'avoue être passé à côter c'est ici que je dois ajouter mes nouveaux champs ?
Il va falloir adapter le controller et le model. Quel sont les quelques fichiers essentiels à modifier dans votre module ?

Screens :

Votre module dans l'Admin prestashop, je voudrais récupérer seulement ce qui est entouré CàD les champs... :

![AdminChamps](https://user-images.githubusercontent.com/53005233/159276557-e35bca37-a278-468a-9fb0-063bc540953a.PNG)

Là où je voudrais le placer côté vendeur (marketplace) remplace ce qui est entouré :

![AdminSellerChamps](https://user-images.githubusercontent.com/53005233/159276564-2a02a6d3-3e09-4c6c-8d13-79323da603bd.PNG)

L'emplacement du fichier tpl qui affiche cette partie où je voudrais voir et utiliser les champs custom
module Knowband hyperlocal marketplace

![ArborescenceKb](https://user-images.githubusercontent.com/53005233/159276569-ac147ce1-a06c-4335-92da-a5e3382b5bca.PNG)

Affichage sur la page produit

![displayChamps_pageProduit](https://user-images.githubusercontent.com/53005233/159276572-7567e75d-4fa7-492d-aaf0-987fa777840e.PNG)

Peut-être utiliser un override, les hooks ...? (mais le fichier shipping.tpl ne semble pas associé à un hook...)
Déplacer certains de vos fichiers de module dans lemodule knowband ?


Merci vraiment pour votre aide, j'espère que je ne vous embête pas trop...
PS : pour le groupe slack il faut adhérer avec une petite contribution c'est bien ça ? (que je ne me trompe pas... ^^)

**Comment by PululuK** [comment]
` PS : pour le groupe slack il faut adhérer avec une petite contribution c'est bien ça ? (que je ne me trompe pas... ^^)`

Non je pense pas !

Pour l'utilization des champs il faut voir la documentation !

**Comment by EliottCrmx** [comment]
Pourquoi fermez-vous aussi vite les topic ?

J'ai réussi à rejoindre le groupe slack, merci, je vais pouvoir apprendre beaucoup et trouver de l'aide.
