### ISSUE TITLE
Prestashop 8.X ?

### ISSUE THREAD

**Issue by iamluxan** [PululuK/democustomfields17#18]
Bonjour,
j'ai installé votre module pour personnaliser certains points d'une fiche produit.

Cependant, rien ne se passe, du coup je me demande si ce module est toujours d'actualité et compatible avec prestashop 8?

Merci !

**Comment by PululuK** [comment]
Bonjour @luxanletexan 

Pourriez-vous donner plus de détails s'il vous plaît ?
C'est compatible sur la version 8.x mais uniquement sur la l'ancienne page et pas sur la experimentale produit.

**Comment by iamluxan** [comment]
Hello Pululuk :-)
merci pour ton retour.

Et bien j'ai pour l'instant tenté d'utiliser le module sans y toucher, c'est à dire avec le fichier HookDisplayAdminProductsExtraFieldsBuilder.php

Voici une capture de l'admin 

![Capture d’écran 2023-09-01 à 11 51 26](https://github.com/PululuK/democustomfields17/assets/1712625/52b1ff74-29e5-40c6-a16e-c0a214e8f067)

**Comment by PululuK** [comment]
Là t'es sur la page experimentale, cela ne marchera pas en effet :) 
Vous utilisez **Prestashop Edition** c'est bien cela ?

**Comment by iamluxan** [comment]
Alors je ne sais pas ce que tu entends par Prestashop Edition ?
Je bosse sur un projet en local avec la version 8.1.0 :)

Y'a pas moyen de forcer l'utilisation de ce module sur cette version ?

**Comment by PululuK** [comment]
Aller dans : **Paramètres avancés >  Fonctionnalités nouvelles et expérimentales.** et désactiver les options  **Nouvelle page produit** 

![Capture d’écran du 2023-09-01 12-16-18](https://github.com/PululuK/democustomfields17/assets/16455155/c550f315-4d68-4616-8a4f-21b57d7b9e5d)

**Comment by iamluxan** [comment]
Merci, je suis passé sur l'ancienne mise en page, mais même après avoir réinitialisé le module je ne vois plus l'onglet "Modules":
![Capture d’écran 2023-09-01 à 12 23 26](https://github.com/PululuK/democustomfields17/assets/1712625/7ff5da28-88ee-4d92-9bf7-70e72cda3f61)

**Comment by PululuK** [comment]
étrange en effet !

**Comment by iamluxan** [comment]
J'ai dû le désactiver, le module me fait planter l'administration des fiches produits. Grr dommage j'aurais bien aimé l'utiliser pour personnaliser certaines choses ;-)

Dans l'attente de prochaines évolutions du coup !

Merci quand même de ton aide!

**Comment by iamluxan** [comment]
Ohh ! Excellent ! je vais tester ça ! :-))))

**Comment by PululuK** [comment]
Tu peux remplacer le contenu de ton fichier `democustomfields17.php` par ça : 

https://raw.githubusercontent.com/PululuK/democustomfields17/main/democustomfields17.php

Si c'est bon pour toi je te fais une release dans la soirée

**Comment by iamluxan** [comment]
J'ai vidé le cache, réinitialiser le module et remplacer le fichier par celui que tu m'as donné, j'ai toujours une erreur 500 sur la page d'édition d'un produit ;)

![Capture d’écran 2023-09-01 à 16 25 09](https://github.com/PululuK/democustomfields17/assets/1712625/c6fd8c55-9bf5-4b6f-a1fb-0bd907dacb7c)

**Comment by PululuK** [comment]
![Capture d’écran du 2023-09-01 16-32-14](https://github.com/PululuK/democustomfields17/assets/16455155/fcb4d36c-ed6b-4f80-94e1-286f76ad4db2)

**Comment by PululuK** [comment]
Sinon dans ce fichier  : 

https://github.com/PululuK/democustomfields17/blob/main/views/PrestaShop/democustomfields17/admin/product/customfields.html.twig#L1

Si vous enlevez cette ligne (et vider le cache) : 

`{% use "PrestaShopBundle:Admin/TwigTemplateForm:bootstrap_4_horizontal_layout.html.twig" %}`

Cela fonctionne ?

**Comment by iamluxan** [comment]
Top, ça marche pour moi !

Merci beaucoup de ta rapidité et de tout ce travail qui facilite grandement la vie ;-)

![Capture d’écran 2023-09-01 à 16 55 16](https://github.com/PululuK/democustomfields17/assets/1712625/d2917db6-e5ae-4fa4-9d26-1111a0ac8045)

**Comment by PululuK** [comment]
@luxanletexan pourriez-vous m'indiquer quelle action a fait fonctionner le module svp ?

**Comment by iamluxan** [comment]
Oui, j'ai retiré la ligne suivante du fichier :
{% use "PrestaShopBundle:Admin/TwigTemplateForm:bootstrap_4_horizontal_layout.html.twig" %}


J'ai ensuite vidé le cache (sinon ça ne foinctionne pas) et c'est tout bon ;)

**Comment by PululuK** [comment]
Parfait alors ! Bon week-end.

**Comment by iamluxan** [comment]
Merci beaucoup, à toi aussi ! Ce module me sauve la mise ! :-)

**Comment by PululuK** [comment]
Cool que cela puisse vous aider !

Je vais sortir une release complet dans quelques mois, vous aurez désormais la possibilité d'ajouter des nouveaux champs directement dans le backoffice.

N'hesite pas à t'abonner pour avoir plus de nouvelles.
