### ISSUE TITLE
Saving and displaying datas

### ISSUE THREAD

**Issue by vmulot** [PululuK/democustomfields17#2]
Hi, it's not really a real issue, but a feature request and help.
I manage to have the field i wanted in Admin Product form, but i can't manage to save it nor have it in the smarty template.
i'm running prestashop 1.7.4.2 on php 7.1.
Are you planning to cover this ? or do you have any advices ?

Thanks a lot

Regards

**Comment by PululuK** [comment]
Hi @vmulot See #4

**Comment by vmulot** [comment]
Very Nice ! thanks a lot ! i'm gonna test :)
